name: bullet39
channels:
  - conda-forge
  - defaults
dependencies:
  - bullet-cpp=3.25
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - icu=75.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=21.1.2
  - libexpat=2.7.1
  - libffi=3.4.6
  - libgfortran=15.2.0w
  - libgfortran5=15.2.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libopenblas=0.3.30
  - libsqlite=3.50.4
  - libxcb=1.17.0
  - libzlib=1.3.1
  - llvm-openmp=21.1.2
  - ncurses=6.5
  - numpy=2.0.2
  - openssl=3.5.4
  - pip=25.2
  - pthread-stubs=0.4
  - pybullet=3.25
  - python=3.9.23
  - python_abi=3.9
  - readline=8.2
  - setuptools=80.9.0
  - tk=8.6.13
  - tzdata=2025b
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
